name: Build and test Node app

on:
  push:
    branches: ["main"]

defaults:
  run:
    working-directory: ./exercises/3-github-actions/app

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: git-checkout
        uses: actions/checkout@v5

      - name: pnpm-setup
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Check for outdated packages
        run: pnpm outdated_check

      - name: Run Prettier
        run: pnpm exec prettify

      - name: Run tests
        run: pnpm exec test
