name: Build and test Node app

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: git-checkout
      - uses: actions/checkout@v5

      - name: pnpm-setup
      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check for outdated packages
        run: pnpm exec outdated --global

      - name: Run Prettier
      - run: pnpm exec prettify

      - name: Run tests
      - run: pnpm exec test
